language: python
sudo: enabled
dist: trusty
group: edge
cache: pip

python:
  - "3.5"

before_install:
  - sudo apt-get install -y python3.5 python3.5-dev
  - sudo rm -f /usr/bin/python
  - sudo rm -f /usr/bin/python3
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3

install:
  - sudo ./install/travis_ci/prepare.sh
  - sudo pip3 install pytest pytest-cov codecov

script:
  - sudo python3 -c 'from jumpscale import j;print(j.application.getMemoryUsage())'
  - sudo pytest -v --cov=Jumpscale Jumpscale

after_success:
  - codecov
