#! /usr/bin/env python3
from js9 import j

import sys
import requests

print(j.do.mascot)

j.clients.redis.start4core()

j.tools.jsloader.removeEggs()

no_init = True
if 'no_init' in sys.argv:
    no_init = False
    sys.argv.pop()

base_repo_url = 'https://github.com/Jumpscale/%s.git'
branch_query_rul = '%s/tree/%s'
branch = 'master'
use_branch =

if len(sys.argv) > 1:
    branch = sys.argv[-1]

def branch_exsit(repo, branch):
    """
    Checks if a branch exist in a git repository
    """
    url = branch_query_rul % (repo, branch)
    response = None
    try:
        response = requests.api.get(url)
        if response.status_code != 200:
            return False
    except Exception:
        pass
    if response is None:
        return False
    return True

for item in ["core9", "lib9", "ays9", "prefab9"]:
    if not branch_exist(item, branch):
        branch = 'master'
    try:
        j.clients.git.pullGitRepo("git@github.com:Jumpscale/%s.git" % item, branch=branch)
    except Exception:
        # try with https
        j.clients.git.pullGitRepo('https://github.com/Jumpscale/%s.git' % item, branch=branch)

    path = "%s/github/jumpscale/%s" % (j.dirs.CODEDIR, item)
    # removes the egg dirs, this to make sure we re-pip, ...
    for dpath in [item for item in j.sal.fs.listDirsInDir(path) if item.lower().find("egg") != -1]:
        j.do.delete(dpath)
    j.do.execute("cd %s;sh install.sh" % path)


if no_init is False:
    print("* init jumpscale 9")
    j.do.execute("js9_init")
