#! /usr/bin/env python3
import sys
from js9 import j

print(j.do.mascot)
j.clients.git.pullGitRepo("git@github.com:Jumpscale/portal9.git")


path = "%s/github/jumpscale/portal9" % j.dirs.CODEDIR
j.do.execute("cd %s;sh install.sh" % path)

if 'noinit' not in sys.argv:
    print("* init jumpscale 9")
    j.do.execute("js9_init")
