#! /usr/bin/env python3


# from js9 import j
# needs to be the original one because am generating the above one
from JumpScale9 import j

try:
    from JumpScale9.data.capnp.Capnp import Capnp
    j.data.capnp = Capnp()
except:
    pass

import sys

print(j.do.mascot)

j.do.debug = False
j.tools.jsloader.generateJumpscalePlugins()
