#! /usr/bin/env python3
from js9 import j
import click

@click.group()
def cli():
    pass

@click.command()
def init():
    j.tools.secretconfig.init()

@click.command()
@click.option('--location', '-l', help='location in jumpscale e.g. j.clients.packetnet (j.clients can be ommitted)')
@click.option('--instance', '-i', help='name of the instance, instance=main')
def configure(location,instance="main"):
    j.tools.secretconfig.configure(location=location,instance=instance)

cli.add_command(configure)
cli.add_command(init)

if __name__ == '__main__':
    cli()
