#! /usr/bin/env python3
from js9 import j
import click

@click.group()
def cli():
    pass

@click.command()
def init():
    j.tools.raml.get(init=True)

@click.command()
@click.option('--reset', '-r', help='reset will delete previously coded server, be carefull', is_flag=True, type=bool)
def generate_pyserver(reset):
    c=j.tools.raml.get()
    c.server_python_generate(reset=reset)

@click.command()
@click.option('--reset', '-r', help='reset will delete previously coded server, be carefull', is_flag=True, type=bool)
def generate_pyclient(reset):
    c=j.tools.raml.get()
    c.client_python_generate(reset=reset)

@click.command()
def start():
    c=j.tools.raml.get()
    c.start()

@click.command()
def reset():
    c=j.tools.raml.get()
    c.reset()

@click.command()
def install():
    j.tools.raml.install()

@click.command()
def upgrade():
    j.tools.raml.upgrade()

@click.command()
def test():
    j.tools.raml.test()


@click.command()
@click.option('--url', '-u', help='url of location where specs are e.g. https://github.com/itsyouonline/identityserver/tree/master/specifications/api')
def getapi(url):
    """
    """
    c=j.tools.raml.get()
    c.specs_get(url)



cli.add_command(install)
cli.add_command(init)
cli.add_command(reset)
cli.add_command(generate_pyserver)
cli.add_command(generate_pyclient)
cli.add_command(start)
cli.add_command(test)
cli.add_command(upgrade)


if __name__ == '__main__':
    cli()
