#! /usr/bin/env python3


# from js9 import j
# needs to be the original one because am generating the above one
from JumpScale9 import j

try:
    from JumpScale9.data.capnp.Capnp import Capnp
    j.data.capnp = Capnp()
except:
    pass

import sys

print(j.do.mascot)

j.do.debug = False
j.tools.jsloader.generatePlugins()

#
#
# todo = []
# todo.append(("lib9", "JumpScale9Lib"))
# todo.append(("core9", "JumpScale9"))
# todo.append(("ays9", "JumpScale9AYS"))
# todo.append(("prefab9", "JumpScale9Prefab"))
# # todo.append(("portal9", "JumpScale9Portal"))
#
# moduleList = {}
#
# for item, libname in todo:
#     path = "%s/github/jumpscale/%s/%s/" % (j.dirs.CODEDIR, item, libname)
#
#     if j.do.exists(path, followlinks=True):
#         moduleList = j.tools.jsloader.findModules(path=path, moduleList=moduleList)
#         # link libs to location for hostos
#         # j.do.symlink(path, "/root/gig/python_libs/%s" % libname, overwriteTarget=True)
#         j.do.copyTree(path, "/root/gig/python_libs/%s" % libname, overwriteFiles=True, ignoredir=['*.egg-info', '*.dist-info', "*JumpScale*", "*Tests*", "*tests*"],
#                       ignorefiles=['*.egg-info', "*.pyc", "*.so", ], rsync=True, recursive=True, rsyncdelete=True, createdir=True)
#
# # DO NOT AUTOPIP the deps are now installed while installing the libs
# # j.application.config["system"]["autopip"] = True
# j.application.config["system"]["debug"] = True
#
# j.tools.jsloader.generate(path=path, moduleList=moduleList)
# j.tools.jsloader.generate(path=path, moduleList=moduleList, codecompleteOnly=True)
#
# j.do.initEnv()
