#! /usr/bin/env python3
from js9 import j
import click

@click.group()
def cli():
    pass

@click.command()
def init():
    j.tools.secretconfig.get()

@click.command()
@click.option('--location', '-l', help='location in jumpscale e.g. j.clients.packetnet (j.clients can be ommitted)')
@click.option('--name', '-n', help='name of the instance, default=default')
def configure(location,name="default"):
    j.tools.secretconfig.configure(location=location,name=name)



cli.add_command(configure)
cli.add_command(init)

if __name__ == '__main__':
    cli()
