#! /usr/bin/env python3
from jumpscale import j
j.tools.bash.local.locale_check()
import click
import sys
# from pprint import pprint as print


logger = j.logger.get("js_doc", force=True)

def path_name_get():
    path=j.sal.fs.getcwd()
    name = j.sal.fs.getBaseName(path)
    
    if name in ["docs","doc"]:
        path2=j.sal.fs.getParent(path)
        name = j.sal.fs.getBaseName(path2)
        
    return path,name
    


@click.group()
def cli():
    pass


@click.command()
def verify():
    """
    verify current directory, will create errors.md
    """
    # j.data.cache.resetAll()
    path,name=path_name_get()
    j.tools.markdowndocs.load(path=path,name=name)
    # ds = j.tools.markdowndocs.docsite_get("info_foundation")
    # ds.doc_get("wallet.md")
    for key,ds in j.tools.markdowndocs.docsites.items():
        ds.verify()
        

cli.add_command(verify)

if __name__ == '__main__':
    cli()
